// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifxpinnsyzdaomkvsqmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmeHBpbm5zeXpkYW9ta3ZzcW1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzQ1NDcsImV4cCI6MjA2NzMxMDU0N30.dxp6kCdgx22YPq4zPwioNrqIyciN4W_2v4HlEEYHnUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});